# Generated by Django 4.0.3 on 2022-04-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
