# Generated by Django 4.0.3 on 2022-04-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_project', '0003_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
    ]
