# Generated by Django 4.0.3 on 2022-05-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_project', '0004_alter_posts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Surname', models.CharField(max_length=10)),
                ('age', models.IntegerField(verbose_name='Age')),
                ('Address', models.CharField(max_length=18)),
                ('Email', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
                ('is_published', models.BooleanField(verbose_name='Remember Password')),
            ],
        ),
    ]
